#ifndef KERNELAES_ENC_H_
#define KERNELAES_ENC_H_

void kernelhotspot1_hp(
float *input_temp,
float *input_temp_noncache,
float *input_power,
float *input_power_noncache,
float *output,
float *output_noncache,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelhotspot2_hp(
float *input_temp,
float *input_temp_noncache,
float *input_power,
float *input_power_noncache,
float *output,
float *output_noncache,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelhotspot3_hp(
float *input_temp,
float *input_temp_noncache,
float *input_power,
float *input_power_noncache,
float *output,
float *output_noncache,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelhotspot4_hp(
float *input_temp,
float *input_temp_noncache,
float *input_power,
float *input_power_noncache,
float *output,
float *output_noncache,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelhotspot1_hpc(
float *input_temp,
float *input_power,
float *output,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelhotspot2_hpc(
float *input_temp,
float *input_power,
float *output,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);


void kernelhotspot3_hpc(
float *input_temp,
float *input_power,
float *output,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);


void kernelhotspot4_hpc(
float *input_temp,
float *input_power,
float *output,
float Cap_1,
float Rx_1,
float Ry_1,
float Rz_1,
int frame_width,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);


#endif 
