connect_bd_net [get_bd_pins sds_irq_const/dout] [get_bd_pins xlconcat_2/In4]
connect_bd_net [get_bd_pins sds_irq_const/dout] [get_bd_pins xlconcat_2/In5]
connect_bd_net [get_bd_pins sds_irq_const/dout] [get_bd_pins xlconcat_2/In6]
connect_bd_net [get_bd_pins sds_irq_const/dout] [get_bd_pins xlconcat_2/In7]
delete_bd_objs [get_bd_nets xlconstant_0_dout]
delete_bd_objs [get_bd_cells xlconstant_0]
connect_bd_net [get_bd_pins gemm1_hp1/ap_done] [get_bd_pins gemm1_hp1_if/ap_done]
connect_bd_net [get_bd_pins gemm1_hp1/ap_done] [get_bd_pins interrupt_generator_0/core_done]
connect_bd_net [get_bd_pins gemm1_hp1_if/ap_start] [get_bd_pins gemm1_hp1/ap_start]
connect_bd_net [get_bd_pins gemm1_hp1_if/ap_idle] [get_bd_pins gemm1_hp1/ap_idle]
connect_bd_net [get_bd_pins gemm1_hp1_if/ap_ready] [get_bd_pins gemm1_hp1/ap_ready]
connect_bd_net [get_bd_pins gemm2_hp2/ap_done] [get_bd_pins gemm2_hp2_if/ap_done]
connect_bd_net [get_bd_pins gemm2_hp2/ap_done] [get_bd_pins interrupt_generator_1/core_done]
connect_bd_net [get_bd_pins gemm2_hp2_if/ap_start] [get_bd_pins gemm2_hp2/ap_start]
connect_bd_net [get_bd_pins gemm2_hp2_if/ap_idle] [get_bd_pins gemm2_hp2/ap_idle]
connect_bd_net [get_bd_pins gemm2_hp2_if/ap_ready] [get_bd_pins gemm2_hp2/ap_ready]
connect_bd_net [get_bd_pins gemm3_hp3/ap_done] [get_bd_pins gemm3_hp3_if/ap_done]
connect_bd_net [get_bd_pins gemm3_hp3/ap_done] [get_bd_pins interrupt_generator_2/core_done]
connect_bd_net [get_bd_pins gemm3_hp3_if/ap_start] [get_bd_pins gemm3_hp3/ap_start]
connect_bd_net [get_bd_pins gemm3_hp3_if/ap_idle] [get_bd_pins gemm3_hp3/ap_idle]
connect_bd_net [get_bd_pins gemm3_hp3_if/ap_ready] [get_bd_pins gemm3_hp3/ap_ready]
connect_bd_net [get_bd_pins gemm4_hp4/ap_done] [get_bd_pins gemm4_hp4_if/ap_done]
connect_bd_net [get_bd_pins gemm4_hp4/ap_done] [get_bd_pins interrupt_generator_3/core_done]
connect_bd_net [get_bd_pins gemm4_hp4_if/ap_start] [get_bd_pins gemm4_hp4/ap_start]
connect_bd_net [get_bd_pins gemm4_hp4_if/ap_idle] [get_bd_pins gemm4_hp4/ap_idle]
connect_bd_net [get_bd_pins gemm4_hp4_if/ap_ready] [get_bd_pins gemm4_hp4/ap_ready]
save_bd_design