void kernelgemm1_hp(
float *array_a,
float *array_a_noncache,
float *array_b,
float *array_b_noncache,
float *array_c,
float *array_c_noncache,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm2_hp(
float *array_a,
float *array_a_noncache,
float *array_b,
float *array_b_noncache,
float *array_c,
float *array_c_noncache,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm3_hp(
float *array_a,
float *array_a_noncache,
float *array_b,
float *array_b_noncache,
float *array_c,
float *array_c_noncache,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm4_hp(
float *array_a,
float *array_a_noncache,
float *array_b,
float *array_b_noncache,
float *array_c,
float *array_c_noncache,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm1_hpc(
float *array_a,
float *array_b,
float *array_c,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm2_hpc(
float *array_a,
float *array_b,
float *array_c,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm3_hpc(
float *array_a,
float *array_b,
float *array_c,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);

void kernelgemm4_hpc(
float *array_a,
float *array_b,
float *array_c,
int mat_dim_fpga,
int file_desc,
int ioctl_flag,
int debug_flag,
int begin,
int end);