# zc702 constraints for LEDs
# IPI-generated HDL wrapper port names leds_tri_o[0:7]
set_property PACKAGE_PIN E15 [get_ports leds_tri_o[7]]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[7]]
set_property PACKAGE_PIN D15 [get_ports leds_tri_o[6] ]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[6] ]
set_property PACKAGE_PIN W17 [get_ports leds_tri_o[5] ]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[5]]
set_property PACKAGE_PIN W5 [get_ports leds_tri_o[4]]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[4]]
set_property PACKAGE_PIN V7 [get_ports leds_tri_o[3]]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[3]]
set_property PACKAGE_PIN W10 [get_ports leds_tri_o[2]]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[2]]
set_property PACKAGE_PIN P18 [get_ports leds_tri_o[1]]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[1]]
set_property PACKAGE_PIN P17 [get_ports leds_tri_o[0]]
set_property IOSTANDARD LVCMOS25 [get_ports leds_tri_o[0]]
